### ISSUE TITLE
node_modules/eskom-loadshedding-api/dist"' has no exported member 'LoadsheddingStatus'. Did you mean 'LoadsheddingStage'?

### ISSUE THREAD

**Issue by ghost** [PolarizedIons/eskom-loadshedding-api#1]
![Capture](https://user-images.githubusercontent.com/17472172/71060879-65217780-216f-11ea-8fa6-16ae2a161b19.PNG)

**Comment by ghost** [comment]
![Capture2](https://user-images.githubusercontent.com/17472172/71060930-871afa00-216f-11ea-941d-ef6c4df9a4fe.PNG)

**Comment by PolarizedIons** [comment]
Hi! Sorry, I seemed to have missed the notification for this issue. 

The README was out of date; I had renamed LoadsheddingStatus to LoadsheddingStage. Fixed now :)
