### ISSUE TITLE
Cannot find module 'eskom-loadshedding-api' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ghost** [PolarizedIons/eskom-loadshedding-api#30]
![image](https://user-images.githubusercontent.com/17472172/118776249-13ab7980-b888-11eb-804c-0257bd362537.png)

Error when trying to use code in documentation.

**Comment by PolarizedIons** [comment]
Hi :)

Did you install the package as a dependency? The phrase 'Cannot find module' makes me think that.

**Comment by ghost** [comment]
I added the dependency and it worked thanks :sweat_smile:
